import { Poppins, KoHo, Noto_Sans_Lao } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./utils/provider";
import Background from "./components/background";
import Header from "./components/header";

const poppins = Poppins({
  weight: "300",
  variable: "--font-poppins",
  subsets: ["latin"],
});

const koho = KoHo({
  weight: "400",
  variable: "--font-koho",
  subsets: ["latin"],
});

const lao = Noto_Sans_Lao({
  weight: "400",
  variable: "--font-lao",
  subsets: ["lao", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
          ${poppins.variable} ${koho.variable}
          ${lao.variable}
          antialiased p-7 relative`
      }>
        <Providers>
          <Background />
          <Header
            headerItems={[
              { label: 'Planos', href: '/plans' },
              { label: 'Sobre Nós', href: '/about' }
            ]}
            isBtn={true}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
