import { Poppins, KoHo, Noto_Sans_Lao } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./utils/provider";
import Background from "./components/background";

const poppins = Poppins({
  weight: "300",
  variable: "--font-poppins",
  subsets: ["latin"],
});

const koho = KoHo({
  weight: "400",
  variable: "--font-koho",
  subsets: ["latin"],
});

const lao = Noto_Sans_Lao({
  weight: "400",
  variable: "--font-lao",
  subsets: ["lao", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`
        ${poppins.variable} ${koho.variable} ${lao.variable}
        antialiased p-7 relative
      `}>
        <Background />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
